#include "rec/gui/icon/MediaPlaybackStart.svg.h"
#include "rec/base/ArraySize.h"
#include "rec/gui/icon/Icon.h"

namespace rec {
namespace gui {
namespace icon {

using juce::Drawable;

// Created by the command line:
// new src/rec/gui/icon/MediaPlaybackStart.svg

Drawable* MediaPlaybackStart::get() {
  static const char data[] = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
  "<!-- Created with Inkscape (http://www.inkscape.org/) -->\n"
  "<svg\n"
  "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
  "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
  "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
  "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
  "   xmlns=\"http://www.w3.org/2000/svg\"\n"
  "   xmlns:xlink=\"http://www.w3.org/1999/xlink\"\n"
  "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
  "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
  "   width=\"48px\"\n"
  "   height=\"48px\"\n"
  "   id=\"svg1307\"\n"
  "   sodipodi:version=\"0.32\"\n"
  "   inkscape:version=\"0.46\"\n"
  "   sodipodi:docbase=\"/home/jimmac/src/cvs/tango-icon-theme/scalable/actions\"\n"
  "   sodipodi:docname=\"media-playback-start.svg\"\n"
  "   inkscape:export-filename=\"/home/lapo/Desktop/Grafica/Icone/media-actions-outlines.png\"\n"
  "   inkscape:export-xdpi=\"90\"\n"
  "   inkscape:export-ydpi=\"90\"\n"
  "   inkscape:output_extension=\"org.inkscape.output.svg.inkscape\">\n"
  "  <defs\n"
  "     id=\"defs1309\">\n"
  "    <inkscape:perspective\n"
  "       sodipodi:type=\"inkscape:persp3d\"\n"
  "       inkscape:vp_x=\"0 : 24 : 1\"\n"
  "       inkscape:vp_y=\"0 : 1000 : 0\"\n"
  "       inkscape:vp_z=\"48 : 24 : 1\"\n"
  "       inkscape:persp3d-origin=\"24 : 16 : 1\"\n"
  "       id=\"perspective49\" />\n"
  "    <linearGradient\n"
  "       id=\"linearGradient2684\">\n"
  "      <stop\n"
  "         id=\"stop2686\"\n"
  "         offset=\"0\"\n"
  "         style=\"stop-color:#ffffff;stop-opacity:1;\" />\n"
  "      <stop\n"
  "         id=\"stop2688\"\n"
  "         offset=\"1\"\n"
  "         style=\"stop-color:#000000;stop-opacity:1;\" />\n"
  "    </linearGradient>\n"
  "    <linearGradient\n"
  "       id=\"linearGradient2584\">\n"
  "      <stop\n"
  "         style=\"stop-color:#000000;stop-opacity:1;\"\n"
  "         offset=\"0\"\n"
  "         id=\"stop2586\" />\n"
  "      <stop\n"
  "         style=\"stop-color:#ffffff;stop-opacity:0;\"\n"
  "         offset=\"1\"\n"
  "         id=\"stop2588\" />\n"
  "    </linearGradient>\n"
  "    <linearGradient\n"
  "       id=\"linearGradient5075\">\n"
  "      <stop\n"
  "         style=\"stop-color:#adb0a8;stop-opacity:1;\"\n"
  "         offset=\"0\"\n"
  "         id=\"stop5077\" />\n"
  "      <stop\n"
  "         style=\"stop-color:#464744;stop-opacity:1\"\n"
  "         offset=\"1\"\n"
  "         id=\"stop5079\" />\n"
  "    </linearGradient>\n"
  "    <linearGradient\n"
  "       id=\"linearGradient2691\"\n"
  "       inkscape:collect=\"always\">\n"
  "      <stop\n"
  "         id=\"stop2693\"\n"
  "         offset=\"0\"\n"
  "         style=\"stop-color:#ffffff;stop-opacity:1\" />\n"
  "      <stop\n"
  "         id=\"stop2695\"\n"
  "         offset=\"1\"\n"
  "         style=\"stop-color:#d3d7cf\" />\n"
  "    </linearGradient>\n"
  "    <linearGradient\n"
  "       id=\"linearGradient3340\">\n"
  "      <stop\n"
  "         style=\"stop-color:#ffffff;stop-opacity:1;\"\n"
  "         offset=\"0\"\n"
  "         id=\"stop3342\" />\n"
  "      <stop\n"
  "         style=\"stop-color:#ffffff;stop-opacity:0.62886596;\"\n"
  "         offset=\"1\"\n"
  "         id=\"stop3344\" />\n"
  "    </linearGradient>\n"
  "    <linearGradient\n"
  "       inkscape:collect=\"always\"\n"
  "       xlink:href=\"#linearGradient5075\"\n"
  "       id=\"linearGradient2306\"\n"
  "       gradientUnits=\"userSpaceOnUse\"\n"
  "       x1=\"71.288956\"\n"
  "       y1=\"124.11652\"\n"
  "       x2=\"70.826942\"\n"
  "       y2=\"95\"\n"
  "       gradientTransform=\"translate(-45.00042,-71.09425)\" />\n"
  "    <radialGradient\n"
  "       inkscape:collect=\"always\"\n"
  "       xlink:href=\"#linearGradient2691\"\n"
  "       id=\"radialGradient2314\"\n"
  "       gradientUnits=\"userSpaceOnUse\"\n"
  "       gradientTransform=\"matrix(5.324342e-2,-0.836238,2.019473,0.128568,-151.9195,108.0768)\"\n"
  "       cx=\"107.5884\"\n"
  "       cy=\"83.990814\"\n"
  "       fx=\"107.5884\"\n"
  "       fy=\"83.990814\"\n"
  "       r=\"12.551644\" />\n"
  "    <linearGradient\n"
  "       inkscape:collect=\"always\"\n"
  "       xlink:href=\"#linearGradient2684\"\n"
  "       id=\"linearGradient2690\"\n"
  "       gradientUnits=\"userSpaceOnUse\"\n"
  "       gradientTransform=\"matrix(1.128181,0,0,1.128181,-53.99314,-83.36009)\"\n"
  "       x1=\"70.913956\"\n"
  "       y1=\"101.74152\"\n"
  "       x2=\"70.951942\"\n"
  "       y2=\"88.923729\" />\n"
  "  </defs>\n"
  "  <sodipodi:namedview\n"
  "     id=\"base\"\n"
  "     pagecolor=\"#ffffff\"\n"
  "     bordercolor=\"#666666\"\n"
  "     borderopacity=\"0.19607843\"\n"
  "     inkscape:pageopacity=\"0.0000000\"\n"
  "     inkscape:pageshadow=\"2\"\n"
  "     inkscape:zoom=\"1\"\n"
  "     inkscape:cx=\"-117.42449\"\n"
  "     inkscape:cy=\"12.980288\"\n"
  "     inkscape:current-layer=\"layer1\"\n"
  "     showgrid=\"false\"\n"
  "     inkscape:grid-bbox=\"true\"\n"
  "     inkscape:document-units=\"px\"\n"
  "     inkscape:grid-points=\"true\"\n"
  "     fill=\"#555753\"\n"
  "     showguides=\"false\"\n"
  "     inkscape:guide-bbox=\"true\"\n"
  "     guidetolerance=\"1px\"\n"
  "     stroke=\"#555753\"\n"
  "     inkscape:window-width=\"872\"\n"
  "     inkscape:window-height=\"688\"\n"
  "     inkscape:window-x=\"326\"\n"
  "     inkscape:window-y=\"160\"\n"
  "     showborder=\"true\"\n"
  "     inkscape:showpageshadow=\"false\">\n"
  "    <sodipodi:guide\n"
  "       orientation=\"horizontal\"\n"
  "       position=\"38.996647\"\n"
  "       id=\"guide2194\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"horizontal\"\n"
  "       position=\"9.0140845\"\n"
  "       id=\"guide2196\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"vertical\"\n"
  "       position=\"9.0140845\"\n"
  "       id=\"guide2198\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"vertical\"\n"
  "       position=\"38.975184\"\n"
  "       id=\"guide2200\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"horizontal\"\n"
  "       position=\"22.988281\"\n"
  "       id=\"guide2202\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"vertical\"\n"
  "       position=\"23.908786\"\n"
  "       id=\"guide2204\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"vertical\"\n"
  "       position=\"157.99417\"\n"
  "       id=\"guide4332\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"horizontal\"\n"
  "       position=\"-36.062446\"\n"
  "       id=\"guide4334\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"horizontal\"\n"
  "       position=\"-58.02695\"\n"
  "       id=\"guide4336\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"vertical\"\n"
  "       position=\"180.00287\"\n"
  "       id=\"guide4338\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"vertical\"\n"
  "       position=\"107.92217\"\n"
  "       id=\"guide4417\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"vertical\"\n"
  "       position=\"129.93087\"\n"
  "       id=\"guide4419\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"horizontal\"\n"
  "       position=\"19.996875\"\n"
  "       id=\"guide5106\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"horizontal\"\n"
  "       position=\"63.039674\"\n"
  "       id=\"guide5119\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"horizontal\"\n"
  "       position=\"49.066305\"\n"
  "       id=\"guide5121\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"horizontal\"\n"
  "       position=\"-86.007168\"\n"
  "       id=\"guide5307\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"horizontal\"\n"
  "       position=\"-108.09009\"\n"
  "       id=\"guide5309\" />\n"
  "    <sodipodi:guide\n"
  "       orientation=\"horizontal\"\n"
  "       position=\"-100.15429\"\n"
  "       id=\"guide3111\" />\n"
  "    <inkscape:grid\n"
  "       id=\"GridFromPre046Settings\"\n"
  "       type=\"xygrid\"\n"
  "       originx=\"0px\"\n"
  "       originy=\"0px\"\n"
  "       spacingx=\"0.5px\"\n"
  "       spacingy=\"0.5px\"\n"
  "       color=\"#0000ff\"\n"
  "       empcolor=\"#0000ff\"\n"
  "       opacity=\"0.2\"\n"
  "       empopacity=\"0.4\"\n"
  "       empspacing=\"2\" />\n"
  "  </sodipodi:namedview>\n"
  "  <metadata\n"
  "     id=\"metadata1312\">\n"
  "    <rdf:RDF>\n"
  "      <cc:Work\n"
  "         rdf:about=\"\">\n"
  "        <dc:format>image/svg+xml</dc:format>\n"
  "        <dc:type\n"
  "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
  "        <dc:title>Media Playback Start</dc:title>\n"
  "        <dc:creator>\n"
  "          <cc:Agent>\n"
  "            <dc:title>Lapo Calamandrei</dc:title>\n"
  "          </cc:Agent>\n"
  "        </dc:creator>\n"
  "        <cc:license\n"
  "           rdf:resource=\"http://creativecommons.org/licenses/publicdomain/\" />\n"
  "        <dc:subject>\n"
  "          <rdf:Bag>\n"
  "            <rdf:li>play</rdf:li>\n"
  "            <rdf:li>media</rdf:li>\n"
  "            <rdf:li>music</rdf:li>\n"
  "            <rdf:li>video</rdf:li>\n"
  "            <rdf:li>player</rdf:li>\n"
  "          </rdf:Bag>\n"
  "        </dc:subject>\n"
  "        <dc:contributor>\n"
  "          <cc:Agent>\n"
  "            <dc:title>Jakub Steiner</dc:title>\n"
  "          </cc:Agent>\n"
  "        </dc:contributor>\n"
  "      </cc:Work>\n"
  "      <cc:License\n"
  "         rdf:about=\"http://creativecommons.org/licenses/publicdomain/\">\n"
  "        <cc:permits\n"
  "           rdf:resource=\"http://creativecommons.org/ns#Reproduction\" />\n"
  "        <cc:permits\n"
  "           rdf:resource=\"http://creativecommons.org/ns#Distribution\" />\n"
  "        <cc:permits\n"
  "           rdf:resource=\"http://creativecommons.org/ns#DerivativeWorks\" />\n"
  "      </cc:License>\n"
  "    </rdf:RDF>\n"
  "  </metadata>\n"
  "  <g\n"
  "     inkscape:groupmode=\"layer\"\n"
  "     id=\"layer4\"\n"
  "     inkscape:label=\"contorno\"\n"
  "     style=\"display:inline\" />\n"
  "  <g\n"
  "     id=\"layer1\"\n"
  "     inkscape:label=\"Layer 1\"\n"
  "     inkscape:groupmode=\"layer\"\n"
  "     style=\"display:inline\">\n"
  "    <path\n"
  "       sodipodi:nodetypes=\"cccc\"\n"
  "       id=\"path2682\"\n"
  "       d=\"M 12,39.5 L 12,9 L 38.06998,23.817079 L 12,39.5 z \"\n"
  "       style=\"color:#000000;fill:none;fill-opacity:1;fill-rule:evenodd;stroke:url(#linearGradient2690);"
  "stroke-width:1.99999833;stroke-linecap:square;stroke-linejoin:round;marker:none;marker-start:none;marker-mid:none;"
  "marker-end:none;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;visibility:visible;"
  "display:inline;overflow:visible;opacity:0.15\"\n"
  "       inkscape:r_cx=\"true\"\n"
  "       inkscape:r_cy=\"true\" />\n"
  "    <path\n"
  "       inkscape:r_cy=\"true\"\n"
  "       inkscape:r_cx=\"true\"\n"
  "       style=\"color:#000000;fill:url(#radialGradient2314);fill-opacity:1;fill-rule:evenodd;stroke:none;"
  "stroke-width:1.00000036;stroke-linecap:square;stroke-linejoin:round;marker:none;marker-start:none;marker-mid:none;"
  "marker-end:none;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;visibility:visible;"
  "display:inline;overflow:visible\"\n"
  "       d=\"M 12.49946,37.81149 L 12.49946,10.000005 L 36.602747,23.905748 L 12.49946,37.81149 z \"\n"
  "       id=\"path3375\"\n"
  "       sodipodi:nodetypes=\"cccc\" />\n"
  "    <path\n"
  "       inkscape:r_cy=\"true\"\n"
  "       inkscape:r_cx=\"true\"\n"
  "       style=\"color:#000000;fill:none;fill-opacity:1;fill-rule:evenodd;stroke:url(#linearGradient2306);"
  "stroke-width:1.00000036;stroke-linecap:square;stroke-linejoin:round;marker:none;marker-start:none;marker-mid:none;"
  "marker-end:none;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;visibility:visible;"
  "display:inline;overflow:visible\"\n"
  "       d=\"M 12.49946,37.81149 L 12.49946,10.000005 L 36.602747,23.905748 L 12.49946,37.81149 z \"\n"
  "       id=\"path2479\"\n"
  "       sodipodi:nodetypes=\"cccc\" />\n"
  "    <path\n"
  "       inkscape:r_cy=\"true\"\n"
  "       inkscape:r_cx=\"true\"\n"
  "       style=\"color:#000000;fill:#ffffff;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:3;"
  "stroke-linecap:square;stroke-linejoin:miter;marker:none;marker-start:none;marker-mid:none;marker-end:none;"
  "stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;visibility:visible;display:inline;"
  "overflow:visible\"\n"
  "       d=\"M 12.99946,10.87449 L 12.99946,36.93699 L 35.59321,23.90574 L 12.99946,10.87449 z M 13.99946,12.62449 L "
  "33.56196,23.90574 L 13.99946,35.18699 L 13.99946,12.62449 z \"\n"
  "       id=\"path2481\"\n"
  "       sodipodi:nodetypes=\"cccccccc\" />\n"
  "    <path\n"
  "       style=\"opacity:0.5;color:#000000;fill:#ffffff;fill-opacity:1;fill-rule:nonzero;stroke:none;stroke-width:2;"
  "stroke-linecap:round;stroke-linejoin:round;marker:none;marker-start:none;marker-mid:none;marker-end:none;"
  "stroke-miterlimit:10;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;visibility:visible;display:block;"
  "overflow:visible\"\n"
  "       d=\"M 13.9375,12.5625 L 13.9375,24.25 C 18.206698,24.205215 23.101656,23.904436 31,22.375 L 13.9375,12.5625 z "
  "\"\n"
  "       id=\"path2339\"\n"
  "       inkscape:r_cx=\"true\"\n"
  "       inkscape:r_cy=\"true\"\n"
  "       sodipodi:nodetypes=\"cccc\" />\n"
  "  </g>\n"
  "</svg>\n"
  " "
;

  static Drawable* d = createFromImageData(data, arraysize(data));
  return d;
};

}  // namespace icon
}  // namespace gui
}  // namespace rec
