// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rec/audio/PlayState.proto

#ifndef PROTOBUF_rec_2faudio_2fPlayState_2eproto__INCLUDED
#define PROTOBUF_rec_2faudio_2fPlayState_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace rec {
namespace audio {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_rec_2faudio_2fPlayState_2eproto();
void protobuf_AssignDesc_rec_2faudio_2fPlayState_2eproto();
void protobuf_ShutdownFile_rec_2faudio_2fPlayState_2eproto();

class PlayState;

// ===================================================================

class PlayState : public ::google::protobuf::Message {
 public:
  PlayState();
  virtual ~PlayState();

  PlayState(const PlayState& from);

  inline PlayState& operator=(const PlayState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayState& default_instance();

  void Swap(PlayState* other);

  // implements Message ----------------------------------------------

  PlayState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayState& from);
  void MergeFrom(const PlayState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline ::google::protobuf::int64 time() const;
  inline void set_time(::google::protobuf::int64 value);

  // optional bool is_playing = 2;
  inline bool has_is_playing() const;
  inline void clear_is_playing();
  static const int kIsPlayingFieldNumber = 2;
  inline bool is_playing() const;
  inline void set_is_playing(bool value);

  // @@protoc_insertion_point(class_scope:rec.audio.PlayState)
 private:
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_is_playing();
  inline void clear_has_is_playing();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 time_;
  bool is_playing_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_rec_2faudio_2fPlayState_2eproto();
  friend void protobuf_AssignDesc_rec_2faudio_2fPlayState_2eproto();
  friend void protobuf_ShutdownFile_rec_2faudio_2fPlayState_2eproto();

  void InitAsDefaultInstance();
  static PlayState* default_instance_;
};
// ===================================================================


// ===================================================================

// PlayState

// optional int64 time = 1;
inline bool PlayState::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayState::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayState::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayState::clear_time() {
  time_ = GOOGLE_LONGLONG(0);
  clear_has_time();
}
inline ::google::protobuf::int64 PlayState::time() const {
  return time_;
}
inline void PlayState::set_time(::google::protobuf::int64 value) {
  set_has_time();
  time_ = value;
}

// optional bool is_playing = 2;
inline bool PlayState::has_is_playing() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PlayState::set_has_is_playing() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PlayState::clear_has_is_playing() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PlayState::clear_is_playing() {
  is_playing_ = false;
  clear_has_is_playing();
}
inline bool PlayState::is_playing() const {
  return is_playing_;
}
inline void PlayState::set_is_playing(bool value) {
  set_has_is_playing();
  is_playing_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace audio
}  // namespace rec

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_rec_2faudio_2fPlayState_2eproto__INCLUDED
