# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rec/util/Mode.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rec/util/Mode.proto',
  package='rec.util',
  serialized_pb='\n\x13rec/util/Mode.proto\x12\x08rec.util\"\xa9\x01\n\x04Mode\x12.\n\x05\x63lick\x18\x01 \x01(\x0e\x32\x15.rec.util.Mode.Action:\x08SET_TIME\"q\n\x06\x41\x63tion\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04\x44RAG\x10\x01\x12\x14\n\x10\x44RAW_LOOP_POINTS\x10\x02\x12\x0c\n\x08SET_TIME\x10\x03\x12\x14\n\x10TOGGLE_SELECTION\x10\x04\x12\x0b\n\x07ZOOM_IN\x10\x05\x12\x0c\n\x08ZOOM_OUT\x10\x06')



_MODE_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='rec.util.Mode.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAG', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAW_LOOP_POINTS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_TIME', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOGGLE_SELECTION', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZOOM_IN', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZOOM_OUT', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=90,
  serialized_end=203,
)


_MODE = _descriptor.Descriptor(
  name='Mode',
  full_name='rec.util.Mode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='click', full_name='rec.util.Mode.click', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MODE_ACTION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=203,
)

_MODE.fields_by_name['click'].enum_type = _MODE_ACTION
_MODE_ACTION.containing_type = _MODE;
DESCRIPTOR.message_types_by_name['Mode'] = _MODE

class Mode(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MODE

  # @@protoc_insertion_point(class_scope:rec.util.Mode)


# @@protoc_insertion_point(module_scope)
