#include "rec/slow/commands/KeyStrokeMap.def.h"

// Created by the command line:
// new --include=command/map/CommandMap.pb --proto=command::KeyStrokeCommandMapProto src/rec/slow/commands/KeyStrokeMap.def

namespace rec {
namespace slow {
namespace commands {

Def<command::KeyStrokeCommandMapProto> keyStrokeMap(
"entry {\n"
  "  type: ABOUT_THIS_PROGRAM\n"
  "  keypress: \"shift + ?\"\n"
  "}\n"
  "entry {\n"
  "  type: ADD_LOOP_POINT\n"
  "  keypress: \"l\"\n"
  "  keypress: \"command + l\"\n"
  "}\n"
  "entry {\n"
  "  type: AUDIO_PREFERENCES\n"
  "  keypress: \"command + ;\"\n"
  "}\n"
  "entry {\n"
  "  type: CLEAR_LOOPS\n"
  "  keypress: \"command + b\"\n"
  "}\n"
  "entry {\n"
  "  type: CLOSE_FILE\n"
  "  keypress: \"command + w\"\n"
  "}\n"
  "entry {\n"
  "  type: COPY\n"
  "  keypress: \"command + c\"\n"
  "}\n"
  "entry {\n"
  "  type: COPY_ALL_LOOP_POINTS\n"
  "  keypress: \"command + c\"\n"
  "}\n"
  "entry {\n"
  "  type: CUT\n"
  "  keypress: \"command + x\"\n"
  "}\n"
  "entry {\n"
  "  type: DEL\n"
  "  keypress: \"delete\"\n"
  "}\n"
  "entry {\n"
  "  type: DESELECT_ALL\n"
  "  keypress: \"command + d\"\n"
  "}\n"
  "entry {\n"
  "  type: EJECT_CDS\n"
  "  keypress: \"command + e\"\n"
  "}\n"
  "entry {\n"
  "  type: INVERT_LOOP_SELECTION\n"
  "  keypress: \"command + i\"\n"
  "}\n"
  "entry {\n"
  "  type: JUMP\n"
  "  keypress: \"\"\n"
  "  keypress: \"\"\n"
  "  keypress: \"\"\n"
  "  keypress: \"\"\n"
  "  keypress: \"\"\n"
  "  keypress: \"1\"\n"
  "  keypress: \"2\"\n"
  "  keypress: \"3\"\n"
  "  keypress: \"4\"\n"
  "  keypress: \"5\"\n"
  "  keypress: \"6\"\n"
  "  keypress: \"7\"\n"
  "  keypress: \"8\"\n"
  "  keypress: \"9\"\n"
  "  keypress: \"0\"\n"
  "  start_index: -5\n"
  "}\n"
  "entry {\n"
  "  type: JUMP_SELECTED\n"
  "  keypress: \"command + cursor left\"\n"
  "  keypress: \"\"\n"
  "  keypress: \"\"\n"
  "  keypress: \"\"\n"
  "  keypress: \"command + cursor right\"\n"
  "  keypress: \"shift + !\"\n"
  "  keypress: \"shift + @\"\n"
  "  keypress: \"shift + #\"\n"
  "  keypress: \"shift + $\"\n"
  "  keypress: \"shift + %\"\n"
  "  keypress: \"shift + ^\"\n"
  "  keypress: \"shift + &\"\n"
  "  keypress: \"shift + *\"\n"
  "  keypress: \"shift + (\"\n"
  "  keypress: \"shift + )\"\n"
  "  start_index: -5\n"
  "}\n"
  "entry {\n"
  "  type: LOOP_NEXT_SEGMENT\n"
  "  keypress: \"n\"\n"
  "}\n"
  "entry {\n"
  "  type: KEYBOARD_MAPPINGS\n"
  "  keypress: \"command + k\"\n"
  "}\n"
  "entry {\n"
  "  type: MIDI_MAPPINGS\n"
  "  keypress: \"command + m\"\n"
  "}\n"
  "entry {\n"
  "  type: MODE_ADD_LOOP_POINT\n"
  "  keypress: \"option + a\"\n"
  "}\n"
  "entry {\n"
  "  type: MODE_DRAG\n"
  "  keypress: \"option + d\"\n"
  "}\n"
  "entry {\n"
  "  type: MODE_SET_TIME\n"
  "  keypress: \"option + t\"\n"
  "}\n"
  "entry {\n"
  "  type: MODE_ZOOM_IN\n"
  "  keypress: \"option + z\"\n"
  "}\n"
  "entry {\n"
  "  type: MUTE_VOLUME_TOGGLE\n"
  "  keypress: \".\"\n"
  "}\n"
  "entry {\n"
  "  type: NUDGE_BACKWARD\n"
  "  keypress: \"cursor left\"\n"
  "}\n"
  "entry {\n"
  "  type: NUDGE_FORWARD\n"
  "  keypress: \"cursor right\"\n"
  "}\n"
  "entry {\n"
  "  type: NUDGE_VOLUME_DOWN\n"
  "  keypress: \"cursor down\"\n"
  "}\n"
  "entry {\n"
  "  type: NUDGE_VOLUME_UP\n"
  "  keypress: \"cursor up\"\n"
  "}\n"
  "entry {\n"
  "  type: NUDGE_SPEED_DOWN\n"
  "  keypress: \"_\"\n"
  "  keypress: \"shift + _\"\n"
  "  keypress: \"-\"\n"
  "}\n"
  "entry {\n"
  "  type: NUDGE_SPEED_UP\n"
  "  keypress: \"+\"\n"
  "  keypress: \"shift + +\"\n"
  "  keypress: \"=\"\n"
  "}\n"
  "entry {\n"
  "  type: OPEN\n"
  "  keypress: \"command + o\"\n"
  "}\n"
  "entry {\n"
  "  type: OPEN_PREVIOUS_FILE\n"
  "  keypress: \"command + r\"\n"
  "}\n"
  "entry {\n"
  "  type: PASTE\n"
  "  keypress: \"command + v\"\n"
  "}\n"
  "entry {\n"
  "  type: PASTE_OVER_LOOP_POINTS\n"
  "  keypress: \"command + v\"\n"
  "}\n"
  "entry {\n"
  "  type: QUIT\n"
  "  keypress: \"command + q\"\n"
  "}\n"
  "entry {\n"
  "  type: REDO\n"
  "  keypress: \"shift + command + z\"\n"
  "}\n"
  "entry {\n"
  "  type: SAVE_FILE\n"
  "  keypress: \"command + s\"\n"
  "}\n"
  "entry {\n"
  "  type: SAVE_FILE_SELECTION\n"
  "  keypress: \"command + shift + s\"\n"
  "}\n"
  "entry {\n"
  "  type: SELECT_ALL\n"
  "  keypress: \"command + a\"\n"
  "}\n"
  "entry {\n"
  "  type: SELECT_ONLY\n"
  "  keypress: \"ctrl + command + cursor left\"\n"
  "  keypress: \"ctrl + cursor left\"\n"
  "  keypress: \"\"\n"
  "  keypress: \"ctrl + cursor right\"\n"
  "  keypress: \"ctrl + command + cursor right\"\n"
  "  start_index: -5\n"
  "}\n"
  "entry {\n"
  "  type: TOGGLE_SELECTION\n"
  "  keypress: \"\"\n"
  "  keypress: \"\"\n"
  "  keypress: \"\"\n"
  "  keypress: \"\"\n"
  "  keypress: \"\"\n"
  "  keypress: \"command + 1\"\n"
  "  keypress: \"command + 2\"\n"
  "  keypress: \"command + 3\"\n"
  "  keypress: \"command + 4\"\n"
  "  keypress: \"command + 5\"\n"
  "  keypress: \"command + 6\"\n"
  "  keypress: \"command + 7\"\n"
  "  keypress: \"command + 8\"\n"
  "  keypress: \"command + 9\"\n"
  "  keypress: \"command + 0\"\n"
  "  start_index: -5\n"
  "}\n"
  "entry {\n"
  "  type: TOGGLE_START_STOP\n"
  "  keypress: \"spacebar\"\n"
  "  keypress: \"return\"\n"
  "}\n"
  "entry {\n"
  "  type: TOGGLE_STRETCH_ENABLE\n"
  "  keypress: \"s\"\n"
  "}\n"
  "entry {\n"
  "  type: TOGGLE_WHOLE_SONG_LOOP\n"
  "  keypress: \"w\"\n"
  "}\n"
  "entry {\n"
  "  type: UNDO\n"
  "  keypress: \"command + z\"\n"
  "}\n"
  "entry {\n"
  "  type: ZOOM_OUT\n"
  "  keypress: \"command + -\"\n"
  "}\n"
  "entry {\n"
  "  type: ZOOM_OUT_FULL\n"
  "  keypress: \"command + shift + -\"\n"
  "}\n"
  "entry {\n"
  "  type: ZOOM_TO_SELECTION\n"
  "  keypress: \"command  + \\'\"\n"
  "  keypress: \"numpad *\"\n"
  "}\n"
  " "
 );

}  // namespace commands
}  // namespace slow
}  // namespace rec
