/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

namespace BinaryData
{

//================== SlowCommands.def ==================
static const unsigned char temp_e71d8a85[] =
"slow_command {\r\n"
"  type: ABOUT_THIS_PROGRAM\r\n"
"  command {\r\n"
"    category: \"Help\"\r\n"
"    desc {\r\n"
"      menu: \"About SlowGold 8\"\r\n"
"      full: \"Bring up a window describing SlowGold 8.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: ADD_LOOP_POINT\r\n"
"  command {\r\n"
"    category: \"Loops\"\r\n"
"    desc {\r\n"
"      menu: \"Add Loop Point At Current Time\"\r\n"
"      full: \"Add a loop point at the current time.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: AUDIO_PREFERENCES\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Audio Preferences...\"\r\n"
"      full: \"Open the Audio Preferences pane.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: CHECK_FOR_UPDATES\r\n"
"  command {\r\n"
"    category: \"Help\"\r\n"
"    desc {\r\n"
"      menu: \"Check For Updates\"\r\n"
"      full: \"Check the World Wide Woodshed website for upgrades to SlowGold 8.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: CLEAR_ALL_SETTINGS\r\n"
"  command {\r\n"
"    category: \"Loops\"\r\n"
"    desc {\r\n"
"      menu: \"Clear All Settings And Quit\"\r\n"
"      full: \"Clear all SlowGold settings for all tracks that have ever been visited and quit the program.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: CLEAR_LOOPS\r\n"
"  command {\r\n"
"    category: \"Loops\"\r\n"
"    desc {\r\n"
"      menu: \"Clear Loops\"\r\n"
"      full: \"Delete all loop points\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: CLEAR_KEYBOARD_MAPPINGS\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Clear Keyboard Mappings\"\r\n"
"      full: \"Clear all keyboard command mappings to program default.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: CLEAR_MIDI_MAPPINGS\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Clear MIDI Mappings\"\r\n"
"      full: \"Clear all MIDI command mappings.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: CLEAR_SETTINGS_FOR_THIS_TRACK\r\n"
"  command {\r\n"
"    category: \"Loops\"\r\n"
"    desc {\r\n"
"      menu: \"Clear Settings For This Track And Quit\"\r\n"
"      full: \"Clear all SlowGold settings for this track only and quit the program.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: CLOSE_FILE\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Close\"\r\n"
"      full: \"Close the current file\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: COPY\r\n"
"  command {\r\n"
"    category: \"Edit\"\r\n"
"    desc {\r\n"
"      menu: \"Copy\"\r\n"
"      full: \"Copy the current selection to the clipboard.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: COPY_ALL_LOOP_POINTS\r\n"
"  command {\r\n"
"    category: \"Edit\"\r\n"
"    desc {\r\n"
"      menu: \"Copy All Loop Points\"\r\n"
"      full: \"Copy both selected and unselected loop points to the clipboard.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: CUT\r\n"
"  command {\r\n"
"    category: \"Edit\"\r\n"
"    desc {\r\n"
"      menu: \"Cut\"\r\n"
"      full: \"Copy the current selection to the clipboard and clear the selection.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: DEL\r\n"
"  command {\r\n"
"    category: \"Edit\"\r\n"
"    desc {\r\n"
"      menu: \"Delete\"\r\n"
"      full: \"Delete the current selection without changing the clipboard.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: DESELECT_ALL\r\n"
"  command {\r\n"
"    category: \"Selection\"\r\n"
"    desc {\r\n"
"      menu: \"Select None\"\r\n"
"      full: \"Select none of the file\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: DIM_VOLUME_TOGGLE\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Toggle audio dim\"\r\n"
"      full: \"Toggle audio dim on and off.\"\r\n"
"   }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: EJECT_CDS\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Eject All\"\r\n"
"      full: \"Eject all CDs and DVDs\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: EXPORT_KEYBOARD_MAPPINGS\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Export Keyboard Command Mappings...\"\r\n"
"      full: \"Export keyboard command mappings.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: EXPORT_MIDI_MAPPINGS\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Export MIDI Command Mappings...\"\r\n"
"      full: \"Export MIDI command mappings.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: EXPORT_SETTINGS\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Export SlowGold Settings...\"\r\n"
"      full: \"Export all SlowGold Settings to a .zip file.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: IMPORT_KEYBOARD_MAPPINGS\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Import Keyboard Command Mappings...\"\r\n"
"      full: \"Import SlowGold keyboard command mappings.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: IMPORT_MIDI_MAPPINGS\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Import MIDI Command Mappings\"\r\n"
"      full: \"Import SlowGold MIDI command mappings.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: IMPORT_SETTINGS\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Import SlowGold Settings...\"\r\n"
"      full: \"Import SlowGold Settings from a .zip file and merge with current settings.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: INVERT_LOOP_SELECTION\r\n"
"  command {\r\n"
"    category: \"Selection\"\r\n"
"    desc {\r\n"
"      menu: \"Invert Selection\"\r\n"
"      full: \"Unselect everything selected and vice-versa.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: JUMP\r\n"
"  command {\r\n"
"    index: 9\r\n"
"    category: \"Transport\"\r\n"
"    desc {\r\n"
"      menu: \"Jump To First Segment\"\r\n"
"      menu: \"Jump To Previous Segment\"\r\n"
"      menu: \"Jump To Current Segment\"\r\n"
"      menu: \"Jump To Next Segment\"\r\n"
"      menu: \"Jump To Last Segment\"\r\n"
"      menu: \"Jump To Segment 1\"\r\n"
"      menu: \"Jump To Segment 2\"\r\n"
"      menu: \"Jump To Segment 3\"\r\n"
"      menu: \"Jump To Segment 4\"\r\n"
"      menu: \"Jump To Segment 5\"\r\n"
"      menu: \"Jump To Segment 6\"\r\n"
"      menu: \"Jump To Segment 7\"\r\n"
"      menu: \"Jump To Segment 8\"\r\n"
"      menu: \"Jump To Segment 9\"\r\n"
"      menu: \"Jump To Segment 10\"\r\n"
"      full: \"Jump to the start of the first segment.\"\r\n"
"      full: \"Jump to the start of the previous segment.\"\r\n"
"      full: \"Jump to the start of the current segment.\"\r\n"
"      full: \"Jump to the start of the next segment.\"\r\n"
"      full: \"Jump to the start of the last segment.\"\r\n"
"      full: \"Jump to the start of segment 1.\"\r\n"
"      full: \"Jump to the start of segment 2.\"\r\n"
"      full: \"Jump to the start of segment 3.\"\r\n"
"      full: \"Jump to the start of segment 4.\"\r\n"
"      full: \"Jump to the start of segment 5.\"\r\n"
"      full: \"Jump to the start of segment 6.\"\r\n"
"      full: \"Jump to the start of segment 7.\"\r\n"
"      full: \"Jump to the start of segment 8.\"\r\n"
"      full: \"Jump to the start of segment 9.\"\r\n"
"      full: \"Jump to the start of segment 10.\"\r\n"
"    }\r\n"
"    start_index: -5\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: JUMP_SELECTED\r\n"
"  command {\r\n"
"    index: 9\r\n"
"    category: \"Transport\"\r\n"
"    desc {\r\n"
"      menu: \"Jump To First Selected Segment\"\r\n"
"      menu: \"Jump To Previous Selected Segment\"\r\n"
"      menu: \"Jump To Current Selected Segment\"\r\n"
"      menu: \"Jump To Next Selected Segment\"\r\n"
"      menu: \"Jump To Last Selected Segment\"\r\n"
"      menu: \"Jump To Selected Segment 1\"\r\n"
"      menu: \"Jump To Selected Segment 2\"\r\n"
"      menu: \"Jump To Selected Segment 3\"\r\n"
"      menu: \"Jump To Selected Segment 4\"\r\n"
"      menu: \"Jump To Selected Segment 5\"\r\n"
"      menu: \"Jump To Selected Segment 6\"\r\n"
"      menu: \"Jump To Selected Segment 7\"\r\n"
"      menu: \"Jump To Selected Segment 8\"\r\n"
"      menu: \"Jump To Selected Segment 9\"\r\n"
"      menu: \"Jump To Selected Segment 10\"\r\n"
"      full: \"Jump To First Selected Segment\"\r\n"
"      full: \"Jump To Previous Selected Segment\"\r\n"
"      full: \"Jump To Current Selected Segment\"\r\n"
"      full: \"Jump To Next Selected Segment\"\r\n"
"      full: \"Jump To Last Selected Segment\"\r\n"
"      full: \"Jump To Selected Segment 1\"\r\n"
"      full: \"Jump To Selected Segment 2\"\r\n"
"      full: \"Jump To Selected Segment 3\"\r\n"
"      full: \"Jump To Selected Segment 4\"\r\n"
"      full: \"Jump To Selected Segment 5\"\r\n"
"      full: \"Jump To Selected Segment 6\"\r\n"
"      full: \"Jump To Selected Segment 7\"\r\n"
"      full: \"Jump To Selected Segment 8\"\r\n"
"      full: \"Jump To Selected Segment 9\"\r\n"
"      full: \"Jump To Selected Segment 10\"\r\n"
"    }\r\n"
"    start_index: -5\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: LOOP_NEXT_SEGMENT\r\n"
"  command {\r\n"
"    category: \"Loops\"\r\n"
"    desc {\r\n"
"      menu: \"Loop Next Segment\"\r\n"
"      full: \"Finish the current segment, then start looping the next segment.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: KEYBOARD_MAPPINGS\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Edit Keyboard Mappings...\"\r\n"
"      full: \"Edit keyboard mappings for commands.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: MIDI_MAPPINGS\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Edit Midi Mappings...\"\r\n"
"      full: \"Edit midi mappings for commands.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: MODE_ADD_LOOP_POINT\r\n"
"  command {\r\n"
"    category: \"Edit\"\r\n"
"    desc {\r\n"
"      menu: \"Add Loop Point Mode\"\r\n"
"      full: \"Enter Add Loop Point Mode, where clicking on the waveform adds a Loop Point at that location.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: MODE_DRAG\r\n"
"  command {\r\n"
"    category: \"Edit\"\r\n"
"    desc {\r\n"
"      menu: \"Drag Mode\"\r\n"
"      full: \"Enter drag mode, where you can drag the waveform back and forth.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: MODE_SET_TIME\r\n"
"  command {\r\n"
"    category: \"Edit\"\r\n"
"    desc {\r\n"
"      menu: \"Set Time Mode\"\r\n"
"      full: \"Enter Set Time Mode, where clicking in the waveform sets the time.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: MODE_ZOOM_IN\r\n"
"  command {\r\n"
"    category: \"Edit\"\r\n"
"    desc {\r\n"
"      menu: \"Zoom In Mode\"\r\n"
"      full: \"Enter Zoom In Mode, where clicking on the waveform zooms in.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: MUTE_VOLUME_TOGGLE\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Toggle audio mute\"\r\n"
"      full: \"Toggle audio mute on and off.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: NUDGE_BACKWARD\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Nudge Backward\"\r\n"
"      full: \"Nudge Backward One Segment Or 10 Seconds\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: NUDGE_FORWARD\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Nudge Forward\"\r\n"
"      full: \"Nudge Forward One Segment Or 10 Seconds\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: NUDGE_VOLUME_DOWN\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Nudge volume down\"\r\n"
"      full: \"Nudge volume down by 2dB\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: NUDGE_VOLUME_UP\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Nudge volume up\"\r\n"
"      full: \"Nudge volume up by 2dB\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: NUDGE_SPEED_DOWN\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Nudge speed down\"\r\n"
"      full: \"Nudge speed down\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: NUDGE_SPEED_UP\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Nudge speed up\"\r\n"
"      full: \"Nudge speed up\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: OPEN\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Open...\"\r\n"
"      full: \"Open a dialog to select a new audio file for looping.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: OPEN_MANUAL\r\n"
"  command {\r\n"
"    category: \"Help\"\r\n"
"    desc {\r\n"
"      menu: \"Download SlowGold 8 User Manual\"\r\n"
"      full: \"Download the SlowGold 8 user manual from the World Wide Woodshed website.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: OPEN_PREVIOUS_FILE\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Re-Open Most Recent Closed File\"\r\n"
"      full: \"Re-open the file that was most recently closed.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: OPEN_SLOWGOLD_DIRECTORY\r\n"
"  command {\r\n"
"    category: \"Help\"\r\n"
"    desc {\r\n"
"      menu: \"Open SlowGold Preferences Directory\"\r\n"
"      full: \"Open the directory where all the SlowGold Preferences Files are located.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: PASTE\r\n"
"  command {\r\n"
"    category: \"Edit\"\r\n"
"    desc {\r\n"
"      menu: \"Paste\"\r\n"
"      full: \"Replace the current selection with a copy of the clipboard.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: PASTE_OVER_LOOP_POINTS\r\n"
"  command {\r\n"
"    category: \"Edit\"\r\n"
"    desc {\r\n"
"      menu: \"Paste Over Loop Points\"\r\n"
"      full: \"Replace all loop points with the loop points on the clipboard.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: QUIT\r\n"
"  command {\r\n"
"    category: \"(None)\"\r\n"
"    desc {\r\n"
"      menu: \"Quit\"\r\n"
"      full: \"Quit SlowGold\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: RECENT_FILES\r\n"
"  command {\r\n"
"    index: 32\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Recent file 1\"\r\n"
"      menu: \"Recent file 2\"\r\n"
"      menu: \"Recent file 3\"\r\n"
"      menu: \"Recent file 4\"\r\n"
"      menu: \"Recent file 5\"\r\n"
"      menu: \"Recent file 6\"\r\n"
"      menu: \"Recent file 7\"\r\n"
"      menu: \"Recent file 8\"\r\n"
"      menu: \"Recent file 9\"\r\n"
"      menu: \"Recent file 10\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      menu: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"      full: \"Recent file\"\r\n"
"    }\r\n"
"    start_index: 0\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: REDO\r\n"
"  command {\r\n"
"    category: \"Edit\"\r\n"
"    desc {\r\n"
"      menu: \"Redo\"\r\n"
"      full: \"Redoes a previously undone command.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: REQUEST_SUPPORT\r\n"
"  command {\r\n"
"    category: \"Help\"\r\n"
"    desc {\r\n"
"      menu: \"Request Technical Support\"\r\n"
"      full: \"Make a request for technical support to World Wide Woodshed.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: RESET_GAIN_TO_UNITY\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Reset Volume\"\r\n"
"      full: \"Reset volume to 0 dB\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: SAVE_FILE\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Save...\"\r\n"
"      full: \"Save the full transformed file in the default save format.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: SAVE_FILE_SELECTION\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Save Selection...\"\r\n"
"      full: \"Save just the selected portion of the transformed file in the default save format.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: SELECT\r\n"
"  command {\r\n"
"    index: 10\r\n"
"    category: \"Selection\"\r\n"
"    desc {\r\n"
"      menu: \"Select First Segment\"\r\n"
"      menu: \"Select Previous Segment\"\r\n"
"      menu: \"Select Current Segment\"\r\n"
"      menu: \"Select Next Segment\"\r\n"
"      menu: \"Select Last Segment\"\r\n"
"      menu: \"Select Segment 1\"\r\n"
"      menu: \"Select Segment 2\"\r\n"
"      menu: \"Select Segment 3\"\r\n"
"      menu: \"Select Segment 4\"\r\n"
"      menu: \"Select Segment 5\"\r\n"
"      menu: \"Select Segment 6\"\r\n"
"      menu: \"Select Segment 7\"\r\n"
"      menu: \"Select Segment 8\"\r\n"
"      menu: \"Select Segment 9\"\r\n"
"      menu: \"Select Segment 10\"\r\n"
"      full: \"Select First Segment\"\r\n"
"      full: \"Select Previous Segment\"\r\n"
"      full: \"Select Current Segment\"\r\n"
"      full: \"Select Next Segment\"\r\n"
"      full: \"Select Last Segment\"\r\n"
"      full: \"Select Segment 1\"\r\n"
"      full: \"Select Segment 2\"\r\n"
"      full: \"Select Segment 3\"\r\n"
"      full: \"Select Segment 4\"\r\n"
"      full: \"Select Segment 5\"\r\n"
"      full: \"Select Segment 6\"\r\n"
"      full: \"Select Segment 7\"\r\n"
"      full: \"Select Segment 8\"\r\n"
"      full: \"Select Segment 9\"\r\n"
"      full: \"Select Segment 10\"\r\n"
"    }\r\n"
"    start_index: -5\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: SELECT_ALL\r\n"
"  command {\r\n"
"    category: \"Transport\"\r\n"
"    desc {\r\n"
"      menu: \"Select All\"\r\n"
"      full: \"Select all of the file\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: SELECT_ONLY\r\n"
"  command {\r\n"
"    index: -1\r\n"
"    category: \"Selection\"\r\n"
"    desc {\r\n"
"      menu: \"Select First Segment Only\"\r\n"
"      menu: \"Select Previous Segment Only\"\r\n"
"      menu: \"Select Current Segment Only\"\r\n"
"      menu: \"Select Next Segment Only\"\r\n"
"      menu: \"Select Last Segment Only\"\r\n"
"      menu: \"Select Segment 1 Only\"\r\n"
"      menu: \"Select Segment 2 Only\"\r\n"
"      menu: \"Select Segment 3 Only\"\r\n"
"      menu: \"Select Segment 4 Only\"\r\n"
"      menu: \"Select Segment 5 Only\"\r\n"
"      menu: \"Select Segment 6 Only\"\r\n"
"      menu: \"Select Segment 7 Only\"\r\n"
"      menu: \"Select Segment 8 Only\"\r\n"
"      menu: \"Select Segment 9 Only\"\r\n"
"      menu: \"Select Segment 10 Only\"\r\n"
"      full: \"Select First Segment Only\"\r\n"
"      full: \"Select Previous Segment Only\"\r\n"
"      full: \"Select Current Segment Only\"\r\n"
"      full: \"Select Next Segment Only\"\r\n"
"      full: \"Select Last Segment Only\"\r\n"
"      full: \"Select Segment 1 Only\"\r\n"
"      full: \"Select Segment 2 Only\"\r\n"
"      full: \"Select Segment 3 Only\"\r\n"
"      full: \"Select Segment 4 Only\"\r\n"
"      full: \"Select Segment 5 Only\"\r\n"
"      full: \"Select Segment 6 Only\"\r\n"
"      full: \"Select Segment 7 Only\"\r\n"
"      full: \"Select Segment 8 Only\"\r\n"
"      full: \"Select Segment 9 Only\"\r\n"
"      full: \"Select Segment 10 Only\"\r\n"
"    }\r\n"
"    start_index: -5\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: SET_SAVE_FORMAT\r\n"
"  command {\r\n"
"    index: 4\r\n"
"    category: \"(None)\"\r\n"
"    desc {\r\n"
"      menu: \"AIFF\"\r\n"
"      menu: \"FLAC\"\r\n"
"      menu: \"Ogg Vorbis\"\r\n"
"      menu: \"WAV\"\r\n"
"      full: \"...\"\r\n"
"      full: \"...\"\r\n"
"      full: \"...\"\r\n"
"      full: \"...\"\r\n"
"    }\r\n"
"    start_index: 0\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: SET_LANGUAGE\r\n"
"  command {\r\n"
"    index: 5\r\n"
"    category: \"(None)\"\r\n"
"    desc {\r\n"
"      menu: \"(None)\"\r\n"
"      menu: \"German\"\r\n"
"      menu: \"English\"\r\n"
"      menu: \"Spanish\"\r\n"
"      menu: \"French\"\r\n"
"      menu: \"Indonesian\"\r\n"
"      full: \"...\"\r\n"
"      full: \"...\"\r\n"
"      full: \"...\"\r\n"
"      full: \"...\"\r\n"
"      full: \"...\"\r\n"
"      full: \"...\"\r\n"
"    }\r\n"
"    start_index: 0\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_ADVANCED_MENUS\r\n"
"  command {\r\n"
"    category: \"File\"\r\n"
"    desc {\r\n"
"      menu: \"Show Advanced Menus\"\r\n"
"      full: \"Toggle show/hide of advanced menus.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"advanced_menus\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.slow.GuiSettings\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_AUTOMATIC_UPDATES\r\n"
"  command {\r\n"
"    category: \"Help\"\r\n"
"    desc {\r\n"
"      menu: \"Enable Automatic Updates\"\r\n"
"      full: \"Enable or disable automatic updates of SlowGold 8.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"auto_check_for_updates\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.slow.GuiSettings\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_COMMAND_BAR_AT_LEFT\r\n"
"  command {\r\n"
"    category: \"Display\"\r\n"
"    desc {\r\n"
"      menu: \"Command Bar At Left Side\"\r\n"
"      full: \"Lay the Command Bar out on the left side of the Waveform Display.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"command_bar_at_left\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.widget.waveform.WaveformProto\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_COMMAND_BAR_AT_TOP\r\n"
"  command {\r\n"
"    category: \"Display\"\r\n"
"    desc {\r\n"
"      menu: \"Command Bar At Top\"\r\n"
"      full: \"Lay the Command Bar out on the top of the Waveform Display.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"command_bar_at_top\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.widget.waveform.WaveformProto\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_FILE_OPEN_TREE_DISPLAY\r\n"
"  command {\r\n"
"    category: \"Display\"\r\n"
"    desc {\r\n"
"      menu: \"Use Tree Display In File Save Dialog\"\r\n"
"      full: \"Use Tree Display In File Save Dialog\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"use_tree_view_in_file_dialogs\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.slow.GuiSettings\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_FOLLOW_CURSOR\r\n"
"  command {\r\n"
"    category: \"Display\"\r\n"
"    desc {\r\n"
"      menu: \"Follow Cursor\"\r\n"
"      full: \"Always keep the time cursor in the window.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"follow_cursor\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.slow.GuiSettings\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_GRID_DISPLAY\r\n"
"  command {\r\n"
"    category: \"Display\"\r\n"
"    desc {\r\n"
"      menu: \"Show Time Gridlines\"\r\n"
"      full: \"Toggle display of the time grid.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"show_grid\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.widget.waveform.WaveformProto\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_MODES_AT_LEFT\r\n"
"  command {\r\n"
"    category: \"Display\"\r\n"
"    desc {\r\n"
"      menu: \"Modes At Left Side\"\r\n"
"      full: \"Lay the Modes display out on the left side of the Waveform Display.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"modes_at_left\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.widget.waveform.WaveformProto\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_MODES_AT_TOP\r\n"
"  command {\r\n"
"    category: \"Display\"\r\n"
"    desc {\r\n"
"      menu: \"Modes At Top\"\r\n"
"      full: \"Lay the Modes display out on the top of the Waveform Display.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"modes_at_top\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.widget.waveform.WaveformProto\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_PARALLEL_WAVEFORMS\r\n"
"  command {\r\n"
"    category: \"Display\"\r\n"
"    desc {\r\n"
"      menu: \"Show Stacked Waveform\"\r\n"
"      full: \"Toggle parallel/stacked waveform display.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"parallel_waveforms\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.widget.waveform.WaveformProto\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_PREFADER_LEVELS\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Show Pre-Fader Levels\"\r\n"
"      full: \"Toggle level display between pre- and post-fader.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      is_global: false\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"prefader_levels\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.audio.Gain\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_SELECTION\r\n"
"  command {\r\n"
"    index: 9\r\n"
"    category: \"Selection\"\r\n"
"    desc {\r\n"
"      menu: \"Toggle First Segment Selection\"\r\n"
"      menu: \"Toggle Previous Segment Selection\"\r\n"
"      menu: \"Toggle Current Segment Selection\"\r\n"
"      menu: \"Toggle Next Segment Selection\"\r\n"
"      menu: \"Toggle Last Segment Selection\"\r\n"
"      menu: \"Toggle Segment Selection 1\"\r\n"
"      menu: \"Toggle Segment Selection 2\"\r\n"
"      menu: \"Toggle Segment Selection 3\"\r\n"
"      menu: \"Toggle Segment Selection 4\"\r\n"
"      menu: \"Toggle Segment Selection 5\"\r\n"
"      menu: \"Toggle Segment Selection 6\"\r\n"
"      menu: \"Toggle Segment Selection 7\"\r\n"
"      menu: \"Toggle Segment Selection 8\"\r\n"
"      menu: \"Toggle Segment Selection 9\"\r\n"
"      menu: \"Toggle Segment Selection 10\"\r\n"
"      full: \"Toggle First Segment Selection\"\r\n"
"      full: \"Toggle Previous Segment Selection\"\r\n"
"      full: \"Toggle Current Segment Selection\"\r\n"
"      full: \"Toggle Next Segment Selection\"\r\n"
"      full: \"Toggle Last Segment Selection\"\r\n"
"      full: \"Toggle Segment Selection 1\"\r\n"
"      full: \"Toggle Segment Selection 2\"\r\n"
"      full: \"Toggle Segment Selection 3\"\r\n"
"      full: \"Toggle Segment Selection 4\"\r\n"
"      full: \"Toggle Segment Selection 5\"\r\n"
"      full: \"Toggle Segment Selection 6\"\r\n"
"      full: \"Toggle Segment Selection 7\"\r\n"
"      full: \"Toggle Segment Selection 8\"\r\n"
"      full: \"Toggle Segment Selection 9\"\r\n"
"      full: \"Toggle Segment Selection 10\"\r\n"
"    }\r\n"
"    start_index: -5\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_SHOW_ABOUT_WINDOW_AT_STARTUP\r\n"
"  command {\r\n"
"    category: \"Help\"\r\n"
"    desc {\r\n"
"      menu: \"Show About Window At Startup\"\r\n"
"      full: \"Toggle whether we show the About Window every time we start up.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"show_about_on_startup\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.slow.GuiSettings\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_SHOW_CURSOR_LABELS\r\n"
"  command {\r\n"
"    category: \"Display\"\r\n"
"    desc {\r\n"
"      menu: \"Show Loop Point Labels\"\r\n"
"      full: \"Show draggable labels for the loop points on the waveform display.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"show_cursor_labels\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.widget.waveform.WaveformProto\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_SHOW_LABELS_AT_TOP\r\n"
"  command {\r\n"
"    category: \"Display\"\r\n"
"    desc {\r\n"
"      menu: \"Show Loop Point Labels At Top\"\r\n"
"      full: \"Show the loop point labels at the top of the waveform display.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"show_labels_at_top\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.widget.waveform.WaveformProto\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_SHOW_MASTER_TUNE\r\n"
"  command {\r\n"
"    category: \"Display\"\r\n"
"    desc {\r\n"
"      menu: \"Show Master Tune Slider\"\r\n"
"      full: \"Show the Master Tune Slider in the Transform Panel.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"show_master_tune\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.slow.GuiSettings\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_SHOW_SELECTION_BUTTONS\r\n"
"  command {\r\n"
"    category: \"Display\"\r\n"
"    desc {\r\n"
"      menu: \"Show Loop Point Selection Buttons\"\r\n"
"      full: \"Show help in help pane.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"show_selection_buttons\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.widget.waveform.WaveformProto\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_SHOW_TIMES_AT_TOP\r\n"
"  command {\r\n"
"    category: \"Display\"\r\n"
"    desc {\r\n"
"      menu: \"Show Grid Times At Top\"\r\n"
"      full: \"Show the grid times for the grid at the top of the waveform display.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"show_times_at_top\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.widget.waveform.WaveformProto\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_START_STOP\r\n"
"  command {\r\n"
"    category: \"Transport\"\r\n"
"    desc {\r\n"
"      menu: \"Toggle Start/Stop\"\r\n"
"      full: \"Start or pause\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_STRETCH_ENABLE\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Enable Stretch\"\r\n"
"      full: \"Toggle between stretched and real-time playback.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      is_global: false\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"time_enabled\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.audio.stretch.Stretch\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_TRANSFORM_ENABLE\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Enable Transforms\"\r\n"
"      full: \"Toggle pitch, time and stereo transforms of the sound.\"\r\n"
"    }\r\n"
"    setter {\r\n"
"      is_global: false\r\n"
"      address {\r\n"
"        part {\r\n"
"          name: \"enabled\"\r\n"
"        }\r\n"
"      }\r\n"
"      type_name: \"rec.audio.stretch.Stretch\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: TOGGLE_WHOLE_SONG_LOOP\r\n"
"  command {\r\n"
"    category: \"Selection\"\r\n"
"    desc {\r\n"
"      menu: \"Loop This Segment\"\r\n"
"      full: \"Toggle selection between the current segment and the whole song.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: UNDO\r\n"
"  command {\r\n"
"    category: \"Edit\"\r\n"
"    desc {\r\n"
"      menu: \"Undo\"\r\n"
"      full: \"Undoes a previous command.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: UNSELECT\r\n"
"  command {\r\n"
"    index: 10\r\n"
"    category: \"Selection\"\r\n"
"    desc {\r\n"
"      menu: \"Unselect First Segment\"\r\n"
"      menu: \"Unselect Previous Segment\"\r\n"
"      menu: \"Unselect Current Segment\"\r\n"
"      menu: \"Unselect Next Segment\"\r\n"
"      menu: \"Unselect Last Segment\"\r\n"
"      menu: \"Unselect Segment 1\"\r\n"
"      menu: \"Unselect Segment 2\"\r\n"
"      menu: \"Unselect Segment 3\"\r\n"
"      menu: \"Unselect Segment 4\"\r\n"
"      menu: \"Unselect Segment 5\"\r\n"
"      menu: \"Unselect Segment 6\"\r\n"
"      menu: \"Unselect Segment 7\"\r\n"
"      menu: \"Unselect Segment 8\"\r\n"
"      menu: \"Unselect Segment 9\"\r\n"
"      menu: \"Unselect Segment 10\"\r\n"
"      full: \"Unselect First Segment\"\r\n"
"      full: \"Unselect Previous Segment\"\r\n"
"      full: \"Unselect Current Segment\"\r\n"
"      full: \"Unselect Next Segment\"\r\n"
"      full: \"Unselect Last Segment\"\r\n"
"      full: \"Unselect Segment 1\"\r\n"
"      full: \"Unselect Segment 2\"\r\n"
"      full: \"Unselect Segment 3\"\r\n"
"      full: \"Unselect Segment 4\"\r\n"
"      full: \"Unselect Segment 5\"\r\n"
"      full: \"Unselect Segment 6\"\r\n"
"      full: \"Unselect Segment 7\"\r\n"
"      full: \"Unselect Segment 8\"\r\n"
"      full: \"Unselect Segment 9\"\r\n"
"      full: \"Unselect Segment 10\"\r\n"
"    }\r\n"
"    start_index: -5\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: WHATS_NEW_PAGE\r\n"
"  command {\r\n"
"    category: \"Help\"\r\n"
"    desc {\r\n"
"      menu: \"What\\'s New In This Release?\"\r\n"
"      full: \"Go to the webpage which tells you what new features and bug fixes are in the release you\\'re running.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: ZOOM_OUT\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Zoom Out\"\r\n"
"      full: \"Zoom out.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: ZOOM_OUT_FULL\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Zoom Out Completely\"\r\n"
"      full: \"Zoom out as far as possible.\"\r\n"
"    }\r\n"
"  }\r\n"
"}\r\n"
"slow_command {\r\n"
"  type: ZOOM_TO_SELECTION\r\n"
"  command {\r\n"
"    category: \"Audio\"\r\n"
"    desc {\r\n"
"      menu: \"Zoom To Selection\"\r\n"
"      full: \"Zoom to selection.\"\r\n"
"    }\r\n"
"  }\r\n"
"}";

const char* SlowCommands_def = (const char*) temp_e71d8a85;

//================== SlowKeyStrokeMap.def ==================
static const unsigned char temp_e4f60ee2[] =
"slow_entry {\r\n"
"  command: ABOUT_THIS_PROGRAM\r\n"
"  entry {\r\n"
"    key: \"shift + ?\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: ADD_LOOP_POINT\r\n"
"  entry {\r\n"
"    key: \"l\"\r\n"
"    key: \"command + l\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: AUDIO_PREFERENCES\r\n"
"  entry {\r\n"
"    key: \"command + ;\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: CLEAR_LOOPS\r\n"
"  entry {\r\n"
"    key: \"command + b\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: CLOSE_FILE\r\n"
"  entry {\r\n"
"    key: \"command + w\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: COPY\r\n"
"  entry {\r\n"
"    key: \"command + c\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: COPY_ALL_LOOP_POINTS\r\n"
"  entry {\r\n"
"    key: \"command + c\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: CUT\r\n"
"  entry {\r\n"
"    key: \"command + x\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: DEL\r\n"
"  entry {\r\n"
"    key: \"delete\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: DESELECT_ALL\r\n"
"  entry {\r\n"
"    key: \"command + d\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: EJECT_CDS\r\n"
"  entry {\r\n"
"    key: \"command + e\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: INVERT_LOOP_SELECTION\r\n"
"  entry {\r\n"
"    key: \"command + i\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP\r\n"
"  entry {\r\n"
"    key: \"1\"\r\n"
"    index: 0\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP\r\n"
"  entry {\r\n"
"    key: \"2\"\r\n"
"    index: 1\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP\r\n"
"  entry {\r\n"
"    key: \"3\"\r\n"
"    index: 2\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP\r\n"
"  entry {\r\n"
"    key: \"4\"\r\n"
"    index: 3\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP\r\n"
"  entry {\r\n"
"    key: \"5\"\r\n"
"    index: 4\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP\r\n"
"  entry {\r\n"
"    key: \"6\"\r\n"
"    index: 5\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP\r\n"
"  entry {\r\n"
"    key: \"7\"\r\n"
"    index: 6\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP\r\n"
"  entry {\r\n"
"    key: \"8\"\r\n"
"    index: 7\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP\r\n"
"  entry {\r\n"
"    key: \"9\"\r\n"
"    index: 8\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP\r\n"
"  entry {\r\n"
"    key: \"0\"\r\n"
"    index: 9\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP_SELECTED\r\n"
"  entry {\r\n"
"    key: \"command + cursor left\"\r\n"
"    index: -5\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP_SELECTED\r\n"
"  entry {\r\n"
"    key: \"command + cursor right\"\r\n"
"    index: -1\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP_SELECTED\r\n"
"  entry {\r\n"
"    key: \"shift + !\"\r\n"
"    index: 0\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP_SELECTED\r\n"
"  entry {\r\n"
"    key: \"shift + @\"\r\n"
"    index: 1\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP_SELECTED\r\n"
"  entry {\r\n"
"    key: \"shift + #\"\r\n"
"    index: 2\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP_SELECTED\r\n"
"  entry {\r\n"
"    key: \"shift + $\"\r\n"
"    index: 3\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP_SELECTED\r\n"
"  entry {\r\n"
"    key: \"shift + %\"\r\n"
"    index: 4\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP_SELECTED\r\n"
"  entry {\r\n"
"    key: \"shift + ^\"\r\n"
"    index: 5\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP_SELECTED\r\n"
"  entry {\r\n"
"    key: \"shift + &\"\r\n"
"    index: 6\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP_SELECTED\r\n"
"  entry {\r\n"
"    key: \"shift + *\"\r\n"
"    index: 7\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP_SELECTED\r\n"
"  entry {\r\n"
"    key: \"shift + (\"\r\n"
"    index: 8\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: JUMP_SELECTED\r\n"
"  entry {\r\n"
"    key: \"shift + )\"\r\n"
"    index: 9\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: LOOP_NEXT_SEGMENT\r\n"
"  entry {\r\n"
"    key: \"n\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: KEYBOARD_MAPPINGS\r\n"
"  entry {\r\n"
"    key: \"command + k\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: MIDI_MAPPINGS\r\n"
"  entry {\r\n"
"    key: \"command + m\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: MODE_ADD_LOOP_POINT\r\n"
"  entry {\r\n"
"    key: \"option + a\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: MODE_DRAG\r\n"
"  entry {\r\n"
"    key: \"option + d\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: MODE_SET_TIME\r\n"
"  entry {\r\n"
"    key: \"option + t\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: MODE_ZOOM_IN\r\n"
"  entry {\r\n"
"    key: \"option + z\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: MUTE_VOLUME_TOGGLE\r\n"
"  entry {\r\n"
"    key: \".\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: NUDGE_BACKWARD\r\n"
"  entry {\r\n"
"    key: \"cursor left\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: NUDGE_FORWARD\r\n"
"  entry {\r\n"
"    key: \"cursor right\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: NUDGE_VOLUME_DOWN\r\n"
"  entry {\r\n"
"    key: \"cursor down\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: NUDGE_VOLUME_UP\r\n"
"  entry {\r\n"
"    key: \"cursor up\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: NUDGE_SPEED_DOWN\r\n"
"  entry {\r\n"
"    key: \"_\"\r\n"
"    key: \"shift + _\"\r\n"
"    key: \"-\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: NUDGE_SPEED_UP\r\n"
"  entry {\r\n"
"    key: \"+\"\r\n"
"    key: \"shift + +\"\r\n"
"    key: \"=\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: OPEN\r\n"
"  entry {\r\n"
"    key: \"command + o\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: OPEN_PREVIOUS_FILE\r\n"
"  entry {\r\n"
"    key: \"command + r\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: PASTE\r\n"
"  entry {\r\n"
"    key: \"command + v\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: PASTE_OVER_LOOP_POINTS\r\n"
"  entry {\r\n"
"    key: \"command + v\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: QUIT\r\n"
"  entry {\r\n"
"    key: \"command + q\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: REDO\r\n"
"  entry {\r\n"
"    key: \"shift + command + z\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: SAVE_FILE\r\n"
"  entry {\r\n"
"    key: \"command + s\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: SAVE_FILE_SELECTION\r\n"
"  entry {\r\n"
"    key: \"command + shift + s\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: SELECT_ALL\r\n"
"  entry {\r\n"
"    key: \"command + a\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: SELECT_ONLY\r\n"
"  entry {\r\n"
"    key: \"ctrl + command + cursor left\"\r\n"
"    index: -5\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: SELECT_ONLY\r\n"
"  entry {\r\n"
"    key: \"ctrl + cursor left\"\r\n"
"    index: -4\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: SELECT_ONLY\r\n"
"  entry {\r\n"
"    key: \"ctrl + cursor right\"\r\n"
"    index: -2\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: SELECT_ONLY\r\n"
"  entry {\r\n"
"    key: \"ctrl + command + cursor right\"\r\n"
"    index: -1\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: TOGGLE_SELECTION\r\n"
"  entry {\r\n"
"    key: \"command + 1\"\r\n"
"    index: 0\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: TOGGLE_SELECTION\r\n"
"  entry {\r\n"
"    key: \"command + 2\"\r\n"
"    index: 1\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: TOGGLE_SELECTION\r\n"
"  entry {\r\n"
"    key: \"command + 3\"\r\n"
"    index: 2\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: TOGGLE_SELECTION\r\n"
"  entry {\r\n"
"    key: \"command + 4\"\r\n"
"    index: 3\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: TOGGLE_SELECTION\r\n"
"  entry {\r\n"
"    key: \"command + 5\"\r\n"
"    index: 4\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: TOGGLE_SELECTION\r\n"
"  entry {\r\n"
"    key: \"command + 6\"\r\n"
"    index: 5\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: TOGGLE_SELECTION\r\n"
"  entry {\r\n"
"    key: \"command + 7\"\r\n"
"    index: 6\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: TOGGLE_SELECTION\r\n"
"  entry {\r\n"
"    key: \"command + 8\"\r\n"
"    index: 7\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: TOGGLE_SELECTION\r\n"
"  entry {\r\n"
"    key: \"command + 9\"\r\n"
"    index: 8\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: TOGGLE_SELECTION\r\n"
"  entry {\r\n"
"    key: \"command + 0\"\r\n"
"    index: 9\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: TOGGLE_START_STOP\r\n"
"  entry {\r\n"
"    key: \"spacebar\"\r\n"
"    key: \"return\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: TOGGLE_STRETCH_ENABLE\r\n"
"  entry {\r\n"
"    key: \"s\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: TOGGLE_WHOLE_SONG_LOOP\r\n"
"  entry {\r\n"
"    key: \"w\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: UNDO\r\n"
"  entry {\r\n"
"    key: \"command + z\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: ZOOM_OUT\r\n"
"  entry {\r\n"
"    key: \"command + -\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: ZOOM_OUT_FULL\r\n"
"  entry {\r\n"
"    key: \"command + shift + -\"\r\n"
"  }\r\n"
"}\r\n"
"slow_entry {\r\n"
"  command: ZOOM_TO_SELECTION\r\n"
"  entry {\r\n"
"    key: \"command  + \\'\"\r\n"
"    key: \"numpad *\"\r\n"
"  }\r\n"
"}";

const char* SlowKeyStrokeMap_def = (const char*) temp_e4f60ee2;

//================== SlowMenuCollection.def ==================
static const unsigned char temp_2e2f7e5a[] =
"menu_bar {\n"
"  description {\n"
"    name: \"basic\"\n"
"  }\n"
"  menu: \"file\"\n"
"  menu: \"edit\"\n"
"  menu: \"audio\"\n"
"  menu: \"transport\"\n"
"  menu: \"select\"\n"
"  menu: \"help\"\n"
"}\n"
"menu_bar {\n"
"  description {\n"
"    name: \"advanced\"\n"
"  }\n"
"  menu: \"file advanced\"\n"
"  menu: \"edit advanced\"\n"
"  menu: \"audio advanced\"\n"
"  menu: \"transport advanced\"\n"
"  menu: \"select advanced\"\n"
"  menu: \"help advanced\"\n"
"}\n";

const char* SlowMenuCollection_def = (const char*) temp_2e2f7e5a;

//================== SlowMenus.def ==================
static const unsigned char temp_9493ace5[] =
"menu {\n"
"  description {\n"
"    name: \"file\"\n"
"  }\n"
"  entry {\n"
"    command: OPEN\n"
"    command: CLOSE_FILE\n"
"    command: EJECT_CDS\n"
"    command: NONE\n"
"    command: TOGGLE_ADVANCED_MENUS\n"
"    command: NONE\n"
"    command: OPEN_PREVIOUS_FILE\n"
"  }\n"
"  entry {\n"
"    is_recent_files_menu: true\n"
"  }\n"
"  entry {\n"
"    command: NONE\n"
"    command: SAVE_FILE\n"
"    command: SAVE_FILE_SELECTION\n"
"  }\n"
"  entry {\n"
"    submenu: \"file type for save\"\n"
"  }\n"
"}\n"
"menu {\n"
"  description {\n"
"    name: \"edit\"\n"
"  }\n"
"  entry {\n"
"    command: UNDO\n"
"    command: REDO\n"
"    command: NONE\n"
"    command: CUT\n"
"    command: COPY\n"
"    command: PASTE\n"
"  }\n"
"}\n"
"menu {\n"
"  description {\n"
"    name: \"audio\"\n"
"  }\n"
"  entry {\n"
"    command: MUTE_VOLUME_TOGGLE\n"
"    command: NUDGE_VOLUME_UP\n"
"    command: NUDGE_VOLUME_DOWN\n"
"    command: NONE\n"
"    command: TOGGLE_STRETCH_ENABLE\n"
"    command: NUDGE_SPEED_UP\n"
"    command: NUDGE_SPEED_DOWN\n"
"    command: NONE\n"
"    command: AUDIO_PREFERENCES\n"
"  }\n"
"}\n"
"menu {\n"
"  description {\n"
"    name: \"transport\"\n"
"  }\n"
"  entry {\n"
"    command: TOGGLE_START_STOP\n"
"    command: ADD_LOOP_POINT\n"
"    command: CLEAR_LOOPS\n"
"  }\n"
"}\n"
"menu {\n"
"  description {\n"
"    name: \"select\"\n"
"  }\n"
"  entry {\n"
"    command: SELECT_ALL\n"
"    command: DESELECT_ALL\n"
"    command: INVERT_LOOP_SELECTION\n"
"    command: TOGGLE_WHOLE_SONG_LOOP\n"
"    command: ZOOM_TO_SELECTION\n"
"  }\n"
"}\n"
"menu {\n"
"  description {\n"
"    name: \"help\"\n"
"  }\n"
"  entry {\n"
"    command: OPEN_MANUAL\n"
"    command: REQUEST_SUPPORT\n"
"    command: WHATS_NEW_PAGE\n"
"  }\n"
"}\n"
"menu {\n"
"  description {\n"
"    name: \"file advanced\"\n"
"  }\n"
"  extends: \"file\"\n"
"  entry {\n"
"    command: NONE\n"
"    command: KEYBOARD_MAPPINGS\n"
"    command: MIDI_MAPPINGS\n"
"    command: NONE\n"
"    command: EXPORT_SETTINGS\n"
"    command: IMPORT_SETTINGS\n"
"  }\n"
"}\n"
"menu {\n"
"  description {\n"
"    name: \"edit advanced\"\n"
"  }\n"
"  extends {\n"
"    name: \"edit\"\n"
"  }\n"
"  entry {\n"
"    command: COPY_ALL_LOOP_POINTS\n"
"    command: PASTE_OVER_LOOP_POINTS\n"
"    command: NONE\n"
"    command: MODE_SET_TIME\n"
"    command: MODE_DRAG\n"
"    command: MODE_ADD_LOOP_POINT\n"
"    command: MODE_ZOOM_IN\n"
"  }\n"
"}\n"
"menu {\n"
"  description {\n"
"    name: \"audio advanced\"\n"
"  }\n"
"  extends: \"audio\"\n"
"}\n"
"menu {\n"
"  description {\n"
"    name: \"transport advanced\"\n"
"  }\n"
"  extends: \"transport\"\n"
"  entry {\n"
"    command: TOGGLE_PREFADER_LEVELS\n"
"  }\n"
"  entry {\n"
"    command: NONE\n"
"    command: JUMP\n"
"    command: JUMP_SELECTED\n"
"    command: NONE\n"
"    command: NUDGE_BACKWARD\n"
"    command: NUDGE_FORWARD\n"
"  }\n"
"}\n"
"menu {\n"
"  description {\n"
"    name: \"select advanced\"\n"
"  }\n"
"  entry {\n"
"    command: NONE\n"
"    command: SELECT\n"
"    command: SELECT_ONLY\n"
"    command: TOGGLE_SELECTION\n"
"    command: UNSELECT\n"
"  }\n"
"}\n"
"menu {\n"
"  description {\n"
"    name: \"help advanced\"\n"
"  }\n"
"  entry {\n"
"    command: TOGGLE_SHOW_ABOUT_WINDOW_AT_STARTUP\n"
"    command: NONE\n"
"    command: CHECK_FOR_UPDATES\n"
"    command: TOGGLE_AUTOMATIC_UPDATES\n"
"  }\n"
"}\n"
"menu {\n"
"  description {\n"
"    name: \"file type for save\"\n"
"  }\n"
"  entry {\n"
"    command: SET_SAVE_AS_AIFF\n"
"    command: SET_SAVE_AS_FLAC\n"
"    command: SET_SAVE_AS_OGG\n"
"    command: SET_SAVE_AS_WAV\n"
"  }\n"
"}\n";

const char* SlowMenus_def = (const char*) temp_9493ace5;


const char* getNamedResource (const char*, int&) throw();
const char* getNamedResource (const char* resourceNameUTF8, int& numBytes) throw()
{
    unsigned int hash = 0;
    if (resourceNameUTF8 != 0)
        while (*resourceNameUTF8 != 0)
            hash = 31 * hash + (unsigned int) *resourceNameUTF8++;

    switch (hash)
    {
        case 0x5863c28f:  numBytes = 29224; return SlowCommands_def;
        case 0x76e9e16c:  numBytes = 6942; return SlowKeyStrokeMap_def;
        case 0xbef1a624:  numBytes = 355; return SlowMenuCollection_def;
        case 0xce3bc719:  numBytes = 2874; return SlowMenus_def;
        default: break;
    }

    numBytes = 0;
    return 0;
}

}
