# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rec/gui/proto/Font.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rec/gui/proto/Font.proto',
  package='rec.gui',
  serialized_pb='\n\x18rec/gui/proto/Font.proto\x12\x07rec.gui\"\x9b\x01\n\tFontProto\x12\x0e\n\x06height\x18\x01 \x01(\x02\x12\x14\n\x0cheight_delta\x18\x02 \x01(\x02\x12\x15\n\rtypeface_name\x18\x03 \x01(\t\x12\x16\n\x0etypeface_style\x18\x04 \x01(\t\x12\x0f\n\x07is_bold\x18\x05 \x01(\x08\x12\x11\n\tis_italic\x18\x06 \x01(\x08\x12\x15\n\ris_underlined\x18\x07 \x01(\x08')




_FONTPROTO = _descriptor.Descriptor(
  name='FontProto',
  full_name='rec.gui.FontProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='rec.gui.FontProto.height', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height_delta', full_name='rec.gui.FontProto.height_delta', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='typeface_name', full_name='rec.gui.FontProto.typeface_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='typeface_style', full_name='rec.gui.FontProto.typeface_style', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_bold', full_name='rec.gui.FontProto.is_bold', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_italic', full_name='rec.gui.FontProto.is_italic', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_underlined', full_name='rec.gui.FontProto.is_underlined', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=38,
  serialized_end=193,
)

DESCRIPTOR.message_types_by_name['FontProto'] = _FONTPROTO

class FontProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FONTPROTO

  # @@protoc_insertion_point(class_scope:rec.gui.FontProto)


# @@protoc_insertion_point(module_scope)
