// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "rec/base/Internat.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace rec {

namespace {

const ::google::protobuf::Descriptor* Internat_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Internat_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Internat_Language_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_rec_2fbase_2fInternat_2eproto() {
  protobuf_AddDesc_rec_2fbase_2fInternat_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "rec/base/Internat.proto");
  GOOGLE_CHECK(file != NULL);
  Internat_descriptor_ = file->message_type(0);
  static const int Internat_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Internat, language_),
  };
  Internat_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Internat_descriptor_,
      Internat::default_instance_,
      Internat_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Internat, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Internat, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Internat));
  Internat_Language_descriptor_ = Internat_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_rec_2fbase_2fInternat_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Internat_descriptor_, &Internat::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_rec_2fbase_2fInternat_2eproto() {
  delete Internat::default_instance_;
  delete Internat_reflection_;
}

void protobuf_AddDesc_rec_2fbase_2fInternat_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027rec/base/Internat.proto\022\003rec\"\213\001\n\010Inter"
    "nat\022,\n\010language\030\001 \001(\0162\026.rec.Internat.Lan"
    "guage:\002EN\"Q\n\010Language\022\010\n\004NONE\020\000\022\006\n\002DE\020\001\022"
    "\006\n\002EN\020\002\022\006\n\002ES\020\003\022\006\n\002FR\020\004\022\006\n\002ID\020\005\022\t\n\005FIRST"
    "\020\001\022\010\n\004LAST\020\005", 172);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "rec/base/Internat.proto", &protobuf_RegisterTypes);
  Internat::default_instance_ = new Internat();
  Internat::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_rec_2fbase_2fInternat_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_rec_2fbase_2fInternat_2eproto {
  StaticDescriptorInitializer_rec_2fbase_2fInternat_2eproto() {
    protobuf_AddDesc_rec_2fbase_2fInternat_2eproto();
  }
} static_descriptor_initializer_rec_2fbase_2fInternat_2eproto_;


// ===================================================================

const ::google::protobuf::EnumDescriptor* Internat_Language_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Internat_Language_descriptor_;
}
bool Internat_Language_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const Internat_Language Internat::NONE;
const Internat_Language Internat::DE;
const Internat_Language Internat::EN;
const Internat_Language Internat::ES;
const Internat_Language Internat::FR;
const Internat_Language Internat::ID;
const Internat_Language Internat::FIRST;
const Internat_Language Internat::LAST;
const Internat_Language Internat::Language_MIN;
const Internat_Language Internat::Language_MAX;
const int Internat::Language_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int Internat::kLanguageFieldNumber;
#endif  // !_MSC_VER

Internat::Internat()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Internat::InitAsDefaultInstance() {
}

Internat::Internat(const Internat& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Internat::SharedCtor() {
  _cached_size_ = 0;
  language_ = 2;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Internat::~Internat() {
  SharedDtor();
}

void Internat::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Internat::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Internat::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Internat_descriptor_;
}

const Internat& Internat::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_rec_2fbase_2fInternat_2eproto();  return *default_instance_;
}

Internat* Internat::default_instance_ = NULL;

Internat* Internat::New() const {
  return new Internat;
}

void Internat::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    language_ = 2;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Internat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .rec.Internat.Language language = 1 [default = EN];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::rec::Internat_Language_IsValid(value)) {
            set_language(static_cast< ::rec::Internat_Language >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Internat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .rec.Internat.Language language = 1 [default = EN];
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->language(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Internat::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .rec.Internat.Language language = 1 [default = EN];
  if (_has_bit(0)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->language(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Internat::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .rec.Internat.Language language = 1 [default = EN];
    if (has_language()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->language());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Internat::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Internat* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Internat*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Internat::MergeFrom(const Internat& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_language(from.language());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Internat::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Internat::CopyFrom(const Internat& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Internat::IsInitialized() const {
  
  return true;
}

void Internat::Swap(Internat* other) {
  if (other != this) {
    std::swap(language_, other->language_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Internat::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Internat_descriptor_;
  metadata.reflection = Internat_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace rec

// @@protoc_insertion_point(global_scope)
