VERSION=0.2.5
URL_PATH=http://yaml-cpp.googlecode.com/files
CONFIGURE="mkdir build && cd build && cmake .."
PREFIX_FLAG=-DCMAKE_INSTALL_PREFIX
CONFIGURE_FLAGS="-DCMAKE_SYSTEM_PROCESSOR=x86 -DBUILD_SHARED_LIBS=0 -DCMAKE_VERBOSE_MAKEFILE=1 -DLIB_TYPE=STATIC"