# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rec/widget/tree/NavigatorConfig.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rec/widget/tree/NavigatorConfig.proto',
  package='rec.widget.tree',
  serialized_pb='\n%rec/widget/tree/NavigatorConfig.proto\x12\x0frec.widget.tree\"{\n\x0fNavigatorConfig\x12\x1e\n\x0f\x61llow_file_drop\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\"\n\x14\x65xpand_to_fit_window\x18\x02 \x01(\x08:\x04true\x12$\n\x16\x63ontract_to_fit_window\x18\x03 \x01(\x08:\x04true')




_NAVIGATORCONFIG = _descriptor.Descriptor(
  name='NavigatorConfig',
  full_name='rec.widget.tree.NavigatorConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='allow_file_drop', full_name='rec.widget.tree.NavigatorConfig.allow_file_drop', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expand_to_fit_window', full_name='rec.widget.tree.NavigatorConfig.expand_to_fit_window', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contract_to_fit_window', full_name='rec.widget.tree.NavigatorConfig.contract_to_fit_window', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=58,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['NavigatorConfig'] = _NAVIGATORCONFIG

class NavigatorConfig(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NAVIGATORCONFIG

  # @@protoc_insertion_point(class_scope:rec.widget.tree.NavigatorConfig)


# @@protoc_insertion_point(module_scope)
