// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rec/slow/GuiSettings.proto

#ifndef PROTOBUF_rec_2fslow_2fGuiSettings_2eproto__INCLUDED
#define PROTOBUF_rec_2fslow_2fGuiSettings_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace rec {
namespace slow {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_rec_2fslow_2fGuiSettings_2eproto();
void protobuf_AssignDesc_rec_2fslow_2fGuiSettings_2eproto();
void protobuf_ShutdownFile_rec_2fslow_2fGuiSettings_2eproto();

class GuiSettings;

// ===================================================================

class GuiSettings : public ::google::protobuf::Message {
 public:
  GuiSettings();
  virtual ~GuiSettings();

  GuiSettings(const GuiSettings& from);

  inline GuiSettings& operator=(const GuiSettings& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GuiSettings& default_instance();

  void Swap(GuiSettings* other);

  // implements Message ----------------------------------------------

  GuiSettings* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GuiSettings& from);
  void MergeFrom(const GuiSettings& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool advanced_menus = 1 [default = false];
  inline bool has_advanced_menus() const;
  inline void clear_advanced_menus();
  static const int kAdvancedMenusFieldNumber = 1;
  inline bool advanced_menus() const;
  inline void set_advanced_menus(bool value);

  // optional bool auto_check_for_updates = 2 [default = true];
  inline bool has_auto_check_for_updates() const;
  inline void clear_auto_check_for_updates();
  static const int kAutoCheckForUpdatesFieldNumber = 2;
  inline bool auto_check_for_updates() const;
  inline void set_auto_check_for_updates(bool value);

  // optional bool drop_adds_to_browser = 3 [default = true];
  inline bool has_drop_adds_to_browser() const;
  inline void clear_drop_adds_to_browser();
  static const int kDropAddsToBrowserFieldNumber = 3;
  inline bool drop_adds_to_browser() const;
  inline void set_drop_adds_to_browser(bool value);

  // optional bool follow_cursor = 4 [default = true];
  inline bool has_follow_cursor() const;
  inline void clear_follow_cursor();
  static const int kFollowCursorFieldNumber = 4;
  inline bool follow_cursor() const;
  inline void set_follow_cursor(bool value);

  // optional bool show_about_on_startup = 5 [default = true];
  inline bool has_show_about_on_startup() const;
  inline void clear_show_about_on_startup();
  static const int kShowAboutOnStartupFieldNumber = 5;
  inline bool show_about_on_startup() const;
  inline void set_show_about_on_startup(bool value);

  // optional bool show_help_pane = 6 [default = true];
  inline bool has_show_help_pane() const;
  inline void clear_show_help_pane();
  static const int kShowHelpPaneFieldNumber = 6;
  inline bool show_help_pane() const;
  inline void set_show_help_pane(bool value);

  // optional bool show_master_tune = 7 [default = false];
  inline bool has_show_master_tune() const;
  inline void clear_show_master_tune();
  static const int kShowMasterTuneFieldNumber = 7;
  inline bool show_master_tune() const;
  inline void set_show_master_tune(bool value);

  // optional bool show_tooltips = 8 [default = false];
  inline bool has_show_tooltips() const;
  inline void clear_show_tooltips();
  static const int kShowTooltipsFieldNumber = 8;
  inline bool show_tooltips() const;
  inline void set_show_tooltips(bool value);

  // optional bool use_tree_view_in_file_dialogs = 9 [default = false];
  inline bool has_use_tree_view_in_file_dialogs() const;
  inline void clear_use_tree_view_in_file_dialogs();
  static const int kUseTreeViewInFileDialogsFieldNumber = 9;
  inline bool use_tree_view_in_file_dialogs() const;
  inline void set_use_tree_view_in_file_dialogs(bool value);

  // optional string last_directory = 10;
  inline bool has_last_directory() const;
  inline void clear_last_directory();
  static const int kLastDirectoryFieldNumber = 10;
  inline const ::std::string& last_directory() const;
  inline void set_last_directory(const ::std::string& value);
  inline void set_last_directory(const char* value);
  inline void set_last_directory(const char* value, size_t size);
  inline ::std::string* mutable_last_directory();
  inline ::std::string* release_last_directory();
  inline void set_allocated_last_directory(::std::string* last_directory);

  // @@protoc_insertion_point(class_scope:rec.slow.GuiSettings)
 private:
  inline void set_has_advanced_menus();
  inline void clear_has_advanced_menus();
  inline void set_has_auto_check_for_updates();
  inline void clear_has_auto_check_for_updates();
  inline void set_has_drop_adds_to_browser();
  inline void clear_has_drop_adds_to_browser();
  inline void set_has_follow_cursor();
  inline void clear_has_follow_cursor();
  inline void set_has_show_about_on_startup();
  inline void clear_has_show_about_on_startup();
  inline void set_has_show_help_pane();
  inline void clear_has_show_help_pane();
  inline void set_has_show_master_tune();
  inline void clear_has_show_master_tune();
  inline void set_has_show_tooltips();
  inline void clear_has_show_tooltips();
  inline void set_has_use_tree_view_in_file_dialogs();
  inline void clear_has_use_tree_view_in_file_dialogs();
  inline void set_has_last_directory();
  inline void clear_has_last_directory();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  bool advanced_menus_;
  bool auto_check_for_updates_;
  bool drop_adds_to_browser_;
  bool follow_cursor_;
  bool show_about_on_startup_;
  bool show_help_pane_;
  bool show_master_tune_;
  bool show_tooltips_;
  ::std::string* last_directory_;
  bool use_tree_view_in_file_dialogs_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];

  friend void  protobuf_AddDesc_rec_2fslow_2fGuiSettings_2eproto();
  friend void protobuf_AssignDesc_rec_2fslow_2fGuiSettings_2eproto();
  friend void protobuf_ShutdownFile_rec_2fslow_2fGuiSettings_2eproto();

  void InitAsDefaultInstance();
  static GuiSettings* default_instance_;
};
// ===================================================================


// ===================================================================

// GuiSettings

// optional bool advanced_menus = 1 [default = false];
inline bool GuiSettings::has_advanced_menus() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GuiSettings::set_has_advanced_menus() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GuiSettings::clear_has_advanced_menus() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GuiSettings::clear_advanced_menus() {
  advanced_menus_ = false;
  clear_has_advanced_menus();
}
inline bool GuiSettings::advanced_menus() const {
  return advanced_menus_;
}
inline void GuiSettings::set_advanced_menus(bool value) {
  set_has_advanced_menus();
  advanced_menus_ = value;
}

// optional bool auto_check_for_updates = 2 [default = true];
inline bool GuiSettings::has_auto_check_for_updates() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GuiSettings::set_has_auto_check_for_updates() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GuiSettings::clear_has_auto_check_for_updates() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GuiSettings::clear_auto_check_for_updates() {
  auto_check_for_updates_ = true;
  clear_has_auto_check_for_updates();
}
inline bool GuiSettings::auto_check_for_updates() const {
  return auto_check_for_updates_;
}
inline void GuiSettings::set_auto_check_for_updates(bool value) {
  set_has_auto_check_for_updates();
  auto_check_for_updates_ = value;
}

// optional bool drop_adds_to_browser = 3 [default = true];
inline bool GuiSettings::has_drop_adds_to_browser() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GuiSettings::set_has_drop_adds_to_browser() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GuiSettings::clear_has_drop_adds_to_browser() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GuiSettings::clear_drop_adds_to_browser() {
  drop_adds_to_browser_ = true;
  clear_has_drop_adds_to_browser();
}
inline bool GuiSettings::drop_adds_to_browser() const {
  return drop_adds_to_browser_;
}
inline void GuiSettings::set_drop_adds_to_browser(bool value) {
  set_has_drop_adds_to_browser();
  drop_adds_to_browser_ = value;
}

// optional bool follow_cursor = 4 [default = true];
inline bool GuiSettings::has_follow_cursor() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GuiSettings::set_has_follow_cursor() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GuiSettings::clear_has_follow_cursor() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GuiSettings::clear_follow_cursor() {
  follow_cursor_ = true;
  clear_has_follow_cursor();
}
inline bool GuiSettings::follow_cursor() const {
  return follow_cursor_;
}
inline void GuiSettings::set_follow_cursor(bool value) {
  set_has_follow_cursor();
  follow_cursor_ = value;
}

// optional bool show_about_on_startup = 5 [default = true];
inline bool GuiSettings::has_show_about_on_startup() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void GuiSettings::set_has_show_about_on_startup() {
  _has_bits_[0] |= 0x00000010u;
}
inline void GuiSettings::clear_has_show_about_on_startup() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void GuiSettings::clear_show_about_on_startup() {
  show_about_on_startup_ = true;
  clear_has_show_about_on_startup();
}
inline bool GuiSettings::show_about_on_startup() const {
  return show_about_on_startup_;
}
inline void GuiSettings::set_show_about_on_startup(bool value) {
  set_has_show_about_on_startup();
  show_about_on_startup_ = value;
}

// optional bool show_help_pane = 6 [default = true];
inline bool GuiSettings::has_show_help_pane() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void GuiSettings::set_has_show_help_pane() {
  _has_bits_[0] |= 0x00000020u;
}
inline void GuiSettings::clear_has_show_help_pane() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void GuiSettings::clear_show_help_pane() {
  show_help_pane_ = true;
  clear_has_show_help_pane();
}
inline bool GuiSettings::show_help_pane() const {
  return show_help_pane_;
}
inline void GuiSettings::set_show_help_pane(bool value) {
  set_has_show_help_pane();
  show_help_pane_ = value;
}

// optional bool show_master_tune = 7 [default = false];
inline bool GuiSettings::has_show_master_tune() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void GuiSettings::set_has_show_master_tune() {
  _has_bits_[0] |= 0x00000040u;
}
inline void GuiSettings::clear_has_show_master_tune() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void GuiSettings::clear_show_master_tune() {
  show_master_tune_ = false;
  clear_has_show_master_tune();
}
inline bool GuiSettings::show_master_tune() const {
  return show_master_tune_;
}
inline void GuiSettings::set_show_master_tune(bool value) {
  set_has_show_master_tune();
  show_master_tune_ = value;
}

// optional bool show_tooltips = 8 [default = false];
inline bool GuiSettings::has_show_tooltips() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void GuiSettings::set_has_show_tooltips() {
  _has_bits_[0] |= 0x00000080u;
}
inline void GuiSettings::clear_has_show_tooltips() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void GuiSettings::clear_show_tooltips() {
  show_tooltips_ = false;
  clear_has_show_tooltips();
}
inline bool GuiSettings::show_tooltips() const {
  return show_tooltips_;
}
inline void GuiSettings::set_show_tooltips(bool value) {
  set_has_show_tooltips();
  show_tooltips_ = value;
}

// optional bool use_tree_view_in_file_dialogs = 9 [default = false];
inline bool GuiSettings::has_use_tree_view_in_file_dialogs() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void GuiSettings::set_has_use_tree_view_in_file_dialogs() {
  _has_bits_[0] |= 0x00000100u;
}
inline void GuiSettings::clear_has_use_tree_view_in_file_dialogs() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void GuiSettings::clear_use_tree_view_in_file_dialogs() {
  use_tree_view_in_file_dialogs_ = false;
  clear_has_use_tree_view_in_file_dialogs();
}
inline bool GuiSettings::use_tree_view_in_file_dialogs() const {
  return use_tree_view_in_file_dialogs_;
}
inline void GuiSettings::set_use_tree_view_in_file_dialogs(bool value) {
  set_has_use_tree_view_in_file_dialogs();
  use_tree_view_in_file_dialogs_ = value;
}

// optional string last_directory = 10;
inline bool GuiSettings::has_last_directory() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void GuiSettings::set_has_last_directory() {
  _has_bits_[0] |= 0x00000200u;
}
inline void GuiSettings::clear_has_last_directory() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void GuiSettings::clear_last_directory() {
  if (last_directory_ != &::google::protobuf::internal::kEmptyString) {
    last_directory_->clear();
  }
  clear_has_last_directory();
}
inline const ::std::string& GuiSettings::last_directory() const {
  return *last_directory_;
}
inline void GuiSettings::set_last_directory(const ::std::string& value) {
  set_has_last_directory();
  if (last_directory_ == &::google::protobuf::internal::kEmptyString) {
    last_directory_ = new ::std::string;
  }
  last_directory_->assign(value);
}
inline void GuiSettings::set_last_directory(const char* value) {
  set_has_last_directory();
  if (last_directory_ == &::google::protobuf::internal::kEmptyString) {
    last_directory_ = new ::std::string;
  }
  last_directory_->assign(value);
}
inline void GuiSettings::set_last_directory(const char* value, size_t size) {
  set_has_last_directory();
  if (last_directory_ == &::google::protobuf::internal::kEmptyString) {
    last_directory_ = new ::std::string;
  }
  last_directory_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GuiSettings::mutable_last_directory() {
  set_has_last_directory();
  if (last_directory_ == &::google::protobuf::internal::kEmptyString) {
    last_directory_ = new ::std::string;
  }
  return last_directory_;
}
inline ::std::string* GuiSettings::release_last_directory() {
  clear_has_last_directory();
  if (last_directory_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = last_directory_;
    last_directory_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void GuiSettings::set_allocated_last_directory(::std::string* last_directory) {
  if (last_directory_ != &::google::protobuf::internal::kEmptyString) {
    delete last_directory_;
  }
  if (last_directory) {
    set_has_last_directory();
    last_directory_ = last_directory;
  } else {
    clear_has_last_directory();
    last_directory_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace slow
}  // namespace rec

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_rec_2fslow_2fGuiSettings_2eproto__INCLUDED
