CONFIGURE="./configure --enable-static --enable-shared=no"
CONFIGURE_CPU_FLAG="--with-cpu=x86"
CONFIGURE_SCRIPT="standard"
CPPFLAGS="-arch i386"
DOWNLOAD="curl -O"
PACKAGES="gflags glog gtest mpg123 protobuf rubberband soundtouch"
PREFIX_FLAG="--prefix"
SUFFIX="tar.bz2"
EXTRACT="tar xjf"
CONFIG_PACKAGES="$PACKAGES"