if [[ "$DEFINE_CPPFLAGS" == "" ]]; then

  CPPFLAGS="$CPPFLAGS"\
  CFLAGS="$CPPFLAGS"\
     $CONFIGURE\
     $CONFIGURE_FLAGS\
     $CONFIGURE_DEBUG_FLAG\
     $CONFIGURE_CPU_FLAG\
     $PREFIX_FLAG="$INSTALL_DIR"

else

  echo "  $CONFIGURE\
     $CONFIGURE_FLAGS\
     $CONFIGURE_DEBUG_FLAG\
     $CONFIGURE_CPU_FLAG\
     CPPFLAGS=$CPPFLAGS\
     $PREFIX_FLAG=\"$INSTALL_DIR\""

  $CONFIGURE\
     $CONFIGURE_FLAGS\
     $CONFIGURE_DEBUG_FLAG\
     $CONFIGURE_CPU_FLAG\
     CPPFLAGS="$CPPFLAGS"\
     $PREFIX_FLAG="$INSTALL_DIR"

fi
