TMP="/tmp"
RM="rm"
LN="ln -s"
GET="wget"
SUFFIX="tar.gz"
EXTRACT="tar xzf"
CONFIGURE="./configure --enable-static --enable-shared=no"
CONFIGURE_CPU_FLAG="--with-cpu=x86"
PREFIX_FLAG="--prefix"
MAKE_CLEAN="make clean"
MAKE_ALL="make"
MAKE_INSTALL="make install"
ARCHIVE_END=""
CPPFLAGS="-arch i386"
CONFIGURE_SCRIPT="standard"

source rec/scripts/platform/platform.sh
