TMP="/tmp"
RM="rm"
LN="ln -s"
GET="wget"
SUFFIX="tar.gz"
EXTRACT="tar xzf"
CONFIGURE="./configure"
CONFIGURE_FLAGS="--with-cpu=x86 --enable-static --enable-shared=no"
PREFIX_FLAG="--prefix"
MAKE_CLEAN="make clean"
MAKE_ALL="make"
MAKE_INSTALL="make install"
ARCHIVE_END=""
CFLAGS="-arch i386"

source rec/scripts/platform/platform.sh
